### ISSUE TITLE
source flag requires source to be in module?

### ISSUE THREAD

**Issue by Thell** [iros/patternfills#10]
```
thell@f38e22ecfb83:~/Projects/SomeKnitrTests$ patternfills -f svg -s ~/SomeKnitrTests/patterns -d patternfills.svg

fs.js:659
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/lib/node_modules/patternfills/src/home/thell/SomeKnitrTests/patterns'
```

Note the path tested...

In `pattern_builder.js` all the path instructions are using joins against `__dirname`. What do you think about testing for, and setting, root prior to calling pattern_builder and using it without modification within pattern_builder?

**Comment by iros** [comment]
Ah, that seems like a good idea.
Any interest in submitting a pull request or this issue? I'd love to get it merged!

**Comment by Thell** [comment]
I'll give it a shot.

**Comment by iros** [comment]
Great! Looking forward to it.

**Comment by Thell** [comment]
@iros,

That helps.  Also, I really like the color options that aren't available on the npm release.

I didn't add in the jsdom dependency and am wondering how you manage to build the patterns without jsdom but with a recent d3.
